module.exports = {
  data: [
    {
      name: 'CF',
      format: '^\\d+[A-Z]$',
    },
    {name: 'CodeChef'},
    {name: 'FHC'},
    {name: 'GCJ'},
    {name: 'HR'},
    {name: 'HE'},
    {name: 'HDU'},
    {name: 'LeetCode'},
    {name: 'LOJ'},
    {name: 'POJ'},
    {name: 'SPOJ'},
    {name: 'TJU'},
    {name: 'Toph'},
    {name: 'URAL'},
    {name: 'URI'},
    {name: 'UVa'},
    {name: 'UVaLive'},
    {name: 'ZOJ'},
  ],
};
